/* Generated by Cython 0.24 */

#ifndef __PYX_HAVE__lutorpy___lupa
#define __PYX_HAVE__lutorpy___lupa


#ifndef __PYX_HAVE_API__lutorpy___lupa

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *char2NumpyArray(char *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *uchar2NumpyArray(unsigned char *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *short2NumpyArray(short *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *int2NumpyArray(int *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *long2NumpyArray(long *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *float2NumpyArray(float *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *double2NumpyArray(double *, PY_LONG_LONG);
__PYX_EXTERN_C DL_IMPORT(PyObject) *copyToNumpyArray(double *, __Pyx_memviewslice, PY_LONG_LONG);

#endif /* !__PYX_HAVE_API__lutorpy___lupa */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_lupa(void);
#else
PyMODINIT_FUNC PyInit__lupa(void);
#endif

#endif /* !__PYX_HAVE__lutorpy___lupa */
